language: java

matrix:
    include:
        -   jdk: openjdk8
            os: linux
        -   jdk: openjdk9
            os: linux
        -   jdk: openjdk10
            os: linux
        -   jdk: openjdk11
            os: linux
        -   jdk: openjdk12
            os: linux

    allow_failures:
        -   jdk: openjdk-ea
            os: linux
        -   jdk: oraclejdk8
            os: linux
            dist: trusty
        -   jdk: oraclejdk11
            os: linux
